#!/usr/bin/env python3
"""Generate today's JLPT data for topic: 比较（优劣、异同、选择）"""
import json
from pathlib import Path

DATA_DIR = Path.home() / "OneDrive" / "ドキュメント" / "apex" / "japanese-data"

# ========== WORDS (40) ==========
words = [
    {"word": "二者択一", "reading": "にゃたくいち", "meaning": "choosing between two options, dilemma", "level": "N2", "isImportant": False, "examples": [{"jp": "二者択一を迫られた。", "en": "I was forced to choose between two options."}, {"jp": "二者択一の状況に陥った。", "en": "I fell into a dilemma."}]},
    {"word": "バランス", "reading": "ばらんす", "meaning": "balance, equilibrium", "level": "N3", "isImportant": False, "examples": [{"jp": "仕事とプライベートのバランスが大切だ。", "en": "Balance between work and private life is important."}, {"jp": "栄養のバランスを考えて食事をする。", "en": "I eat with nutritional balance in mind."}]},
    {"word": "メリット", "reading": "めりっと", "meaning": "merit, advantage, benefit", "level": "N3", "isImportant": False, "examples": [{"jp": "この制度には多くのメリットがある。", "en": "This system has many merits."}, {"jp": "メリットとデメリットを比較する。", "en": "Compare merits and demerits."}]},
    {"word": "デメリット", "reading": "でめりっと", "meaning": "demerit, disadvantage, drawback", "level": "N3", "isImportant": False, "examples": [{"jp": "この方法のデメリットは何ですか。", "en": "What are the disadvantages of this method?"}, {"jp": "デメリットが大きすぎる。", "en": "The drawbacks are too big."}]},
    {"word": "トレードオフ", "reading": "とれーどおふ", "meaning": "trade-off", "level": "N1", "isImportant": False, "examples": [{"jp": "品質とコストはトレードオフの関係にある。", "en": "Quality and cost have a trade-off relationship."}, {"jp": "トレードオフを理解する必要がある。", "en": "You need to understand the trade-off."}]},
    {"word": "あがる", "reading": "あがる", "meaning": "to rise, to go up", "level": "N4", "isImportant": False, "examples": [{"jp": "気温があがってきた。", "en": "The temperature has risen."}, {"jp": "品質があがった。", "en": "The quality has improved."}]},
    {"word": "さがる", "reading": "さがる", "meaning": "to fall, to go down, to decline", "level": "N4", "isImportant": False, "examples": [{"jp": "気温がさがってきた。", "en": "The temperature has fallen."}, {"jp": "評価がさがった。", "en": "The evaluation declined."}]},
    {"word": "上等", "reading": "じょうとう", "meaning": "first-class, superior, best quality", "level": "N2", "isImportant": False, "examples": [{"jp": "上等のワインを注文した。", "en": "I ordered a first-class wine."}, {"jp": "この商品は上等だ。", "en": "This product is top quality."}]},
    {"word": "下等", "reading": "かとう", "meaning": "inferior, low class, base", "level": "N1", "isImportant": False, "examples": [{"jp": "下等な考え方だ。", "en": "That's an inferior way of thinking."}, {"jp": "下等な行動をとる。", "en": "To take base actions."}]},
    {"word": "良し悪し", "reading": "よしあし", "meaning": "good and bad, pros and cons", "level": "N2", "isImportant": False, "examples": [{"jp": "計画の良し悪しを検討する。", "en": "Examine the pros and cons of the plan."}, {"jp": "物事の良し悪しは一概には言えない。", "en": "You can't say whether things are good or bad across the board."}]},
    {"word": "程よい", "reading": "ほどよい", "meaning": "moderate, proper, just right", "level": "N3", "isImportant": False, "examples": [{"jp": "程よい緊張感が大切だ。", "en": "Moderate tension is important."}, {"jp": "程よい距離感を保つ。", "en": "Maintain a moderate distance."}]},
    {"word": "適切", "reading": "てきせつ", "meaning": "appropriate, suitable, adequate", "level": "N2", "isImportant": False, "examples": [{"jp": "適切な対応をとる。", "en": "Take appropriate measures."}, {"jp": "適切なタイミングで発表した。", "en": "Announced at the right time."}]},
    {"word": "ふさわしい", "reading": "ふさわしい", "meaning": "suitable, appropriate, becoming", "level": "N3", "isImportant": False, "examples": [{"jp": "リーダーにふさわしい人だ。", "en": "He is suitable as a leader."}, {"jp": "場にふさわしい服装をする。", "en": "Wear clothes suitable for the occasion."}]},
    {"word": "そっくり", "reading": "そっくり", "meaning": "exactly alike, identical, similar", "level": "N3", "isImportant": False, "examples": [{"jp": "母にそっくりな娘だ。", "en": "A daughter exactly like her mother."}, {"jp": "そっくりそのまま真似した。", "en": "Copied it exactly as is."}]},
    {"word": "まねる", "reading": "まねる", "meaning": "to mimic, to imitate, to copy", "level": "N3", "isImportant": False, "examples": [{"jp": "先生の話し方をまねる。", "en": "Imitate the teacher's way of speaking."}, {"jp": "有名人をまねて遊ぶ。", "en": "Play imitating a celebrity."}]},
    {"word": "かたよる", "reading": "かたよる", "meaning": "to be biased, to lean, to be one-sided", "level": "N2", "isImportant": False, "examples": [{"jp": "考えがかたよっている。", "en": "Your thinking is biased."}, {"jp": "栄養がかたよった食事だ。", "en": "It's a nutritionally unbalanced meal."}]},
    {"word": "均等", "reading": "きんとう", "meaning": "equal, even, uniform", "level": "N2", "isImportant": False, "examples": [{"jp": "均等に分配する。", "en": "Distribute equally."}, {"jp": "均等な機会を与える。", "en": "Give equal opportunities."}]},
    {"word": "バラバラ", "reading": "ばらばら", "meaning": "scattered, scattered about, disjointed", "level": "N3", "isImportant": False, "examples": [{"jp": "意見がバラバラだ。", "en": "Opinions are divided."}, {"jp": "部屋の中がバラバラになっている。", "en": "The room is in disarray."}]},
    {"word": "微妙", "reading": "びみょう", "meaning": "subtle, delicate, questionable", "level": "N3", "isImportant": False, "examples": [{"jp": "微妙な違いがある。", "en": "There is a subtle difference."}, {"jp": "微妙な雰囲気だ。", "en": "It's a delicate atmosphere."}]},
    {"word": "顕著", "reading": "けんちょ", "meaning": "remarkable, striking, conspicuous", "level": "N1", "isImportant": False, "examples": [{"jp": "顕著な違いが見られる。", "en": "A remarkable difference can be seen."}, {"jp": "顕著な効果を上げた。", "en": "Achieved a striking effect."}]},
    {"word": "はっきり", "reading": "はっきり", "meaning": "clearly, distinctly, plainly", "level": "N4", "isImportant": False, "examples": [{"jp": "はっきりと違いがわかる。", "en": "You can clearly tell the difference."}, {"jp": "はっきり言ってください。", "en": "Please say it clearly."}]},
    {"word": "ぼんやり", "reading": "ぼんやり", "meaning": "dimly, vaguely, absent-mindedly", "level": "N3", "isImportant": False, "examples": [{"jp": "ぼんやりとしか覚えていない。", "en": "I only vaguely remember."}, {"jp": "ぼんやりした印象を与える。", "en": "It gives a vague impression."}]},
    {"word": "際立つ", "reading": "きわだつ", "meaning": "to stand out, to be conspicuous, to be prominent", "level": "N2", "isImportant": False, "examples": [{"jp": "彼は際立った才能を持っている。", "en": "He has outstanding talent."}, {"jp": "白いドレスが際立っている。", "en": "The white dress stands out."}]},
    {"word": "匹敵", "reading": "ひってき", "meaning": "to match, to be comparable, to rival", "level": "N1", "isImportant": False, "examples": [{"jp": "彼に匹敵する人はいない。", "en": "There is no one who can match him."}, {"jp": "匹敵する性能を持つ。", "en": "Have comparable performance."}]},
    {"word": "及ばない", "reading": "およばない", "meaning": "to not reach, to be inferior to, to not match", "level": "N2", "isImportant": False, "examples": [{"jp": "昔の品質には及ばない。", "en": "It doesn't reach the quality of the past."}, {"jp": "彼には到底及ばない。", "en": "I'm no match for him at all."}]},
    {"word": "凌ぐ", "reading": "しのぐ", "meaning": "to endure, to overcome, to outdo", "level": "N1", "isImportant": False, "examples": [{"jp": "困難を凌ぐ。", "en": "Overcome difficulties."}, {"jp": "競合を凌いで一位になる。", "en": "Outdo the competition and become number one."}]},
    {"word": "優越", "reading": "ゆうえつ", "meaning": "superiority, supremacy", "level": "N1", "isImportant": False, "examples": [{"jp": "優越感を持つ。", "en": "Have a sense of superiority."}, {"jp": "技術的な優越を保つ。", "en": "Maintain technical superiority."}]},
    {"word": "優先", "reading": "ゆうせん", "meaning": "preference, priority, precedence", "level": "N2", "isImportant": False, "examples": [{"jp": "安全を優先する。", "en": "Give priority to safety."}, {"jp": "優先順位をつける。", "en": "Set priorities."}]},
    {"word": "劣後", "reading": "れつご", "meaning": "subordination, junior claim, inferiority", "level": "N1", "isImportant": False, "examples": [{"jp": "劣後債を発行する。", "en": "Issue subordinated bonds."}, {"jp": "劣後する立場にある。", "en": "Be in a subordinate position."}]},
    {"word": "対等", "reading": "たいとう", "meaning": "equal, equivalent, on equal terms", "level": "N2", "isImportant": False, "examples": [{"jp": "対等な立場で話し合う。", "en": "Discuss on equal terms."}, {"jp": "対等な関係を築く。", "en": "Build an equal relationship."}]},
    {"word": "不平等", "reading": "ふびょうどう", "meaning": "inequality, unfairness, disparity", "level": "N2", "isImportant": False, "examples": [{"jp": "不平等な扱いを受ける。", "en": "Receive unequal treatment."}, {"jp": "不平等を解消する。", "en": "Eliminate inequality."}]},
    {"word": "格差", "reading": "かくさ", "meaning": "gap, disparity, difference in status", "level": "N1", "isImportant": False, "examples": [{"jp": "収入の格差が広がっている。", "en": "The income gap is widening."}, {"jp": "格差社会の問題。", "en": "Problems of a disparity society."}]},
    {"word": "隔たり", "reading": "へだたり", "meaning": "distance, gap, estrangement", "level": "N1", "isImportant": False, "examples": [{"jp": "大きな隔たりがある。", "en": "There is a big gap."}, {"jp": "世代間の隔たりを埋める。", "en": "Bridge the generation gap."}]},
    {"word": "大差", "reading": "たいさ", "meaning": "big difference, wide margin", "level": "N2", "isImportant": False, "examples": [{"jp": "大差で勝った。", "en": "Won by a wide margin."}, {"jp": "大差がつく。", "en": "A big difference is made."}]},
    {"word": "僅差", "reading": "きんさ", "meaning": "close margin, narrow difference", "level": "N1", "isImportant": False, "examples": [{"jp": "僅差で負けた。", "en": "Lost by a narrow margin."}, {"jp": "僅差の勝利だった。", "en": "It was a close victory."}]},
    {"word": "類似", "reading": "るいじ", "meaning": "similarity, resemblance, analogy", "level": "N2", "isImportant": False, "examples": [{"jp": "類似の事例を探す。", "en": "Look for similar cases."}, {"jp": "類似点が多い。", "en": "There are many similarities."}]},
    {"word": "相違", "reading": "そうい", "meaning": "difference, discrepancy, divergence", "level": "N2", "isImportant": False, "examples": [{"jp": "大きな相違がある。", "en": "There is a big difference."}, {"jp": "相違点を明確にする。", "en": "Clarify the differences."}]},
    {"word": "差異", "reading": "さい", "meaning": "difference, disparity, divergence", "level": "N1", "isImportant": False, "examples": [{"jp": "文化的な差異を理解する。", "en": "Understand cultural differences."}, {"jp": "差異を認める。", "en": "Acknowledge the difference."}]},
    {"word": "互角", "reading": "ごかく", "meaning": "equal, even match, on par", "level": "N1", "isImportant": False, "examples": [{"jp": "互角の戦いだった。", "en": "It was an even match."}, {"jp": "互角の実力を持つ。", "en": "Have equal ability."}]},
    {"word": "拮抗", "reading": "きっこう", "meaning": "rivalry, competition, being on equal terms", "level": "N1", "isImportant": False, "examples": [{"jp": "二つの会社が拮抗している。", "en": "Two companies are competing."}, {"jp": "拮抗する勢力が存在する。", "en": "There are rival forces."}]},
]

# ========== GRAMMAR (20) ==========
grammar = [
    {"title": "～にまさる", "meaning": "surpassing~, better than~, superior to~", "level": "N1", "isImportant": False, "expressions": ["～にまさる", "～にまさるものはない"], "patterns": ["Noun + にまさる", "Noun + にまさるものはない"], "examples": [{"jp": "彼にまさる選手はいない。", "en": "There is no player better than him."}, {"jp": "この味にまさるものはない。", "en": "Nothing surpasses this taste."}], "notes": "Used to express that something/someone is the best or unsurpassed."},
    {"title": "～に及ばない", "meaning": "not reaching~, not as good as~, no match for~", "level": "N1", "isImportant": False, "expressions": ["～に及ばない", "～には及ばない"], "patterns": ["Noun + に及ばない", "Noun + には及ばない"], "examples": [{"jp": "昔の品質には及ばない。", "en": "It doesn't reach the quality of the past."}, {"jp": "彼には到底及ばない。", "en": "I'm no match for him at all."}], "notes": "Expresses inferiority or inability to match."},
    {"title": "～にひきかえ", "meaning": "in contrast to~, unlike~, as opposed to~", "level": "N2", "isImportant": False, "expressions": ["～にひきかえ", "～にひきかえて"], "patterns": ["Noun/Verb + にひきかい", "Noun/Verb + にひきかえ"], "examples": [{"jp": "兄にひきかえ、弟はとても活発だ。", "en": "In contrast to the older brother, the younger brother is very active."}, {"jp": "昨日にひきかえ、今日は天気がいい。", "en": "Unlike yesterday, the weather is nice today."}], "notes": "Used to contrast two things, showing they are different."},
    {"title": "～にもまさる", "meaning": "surpassing~, exceeding~, better than~", "level": "N1", "isImportant": False, "expressions": ["～にもまさる", "～にもまさるものはない"], "patterns": ["Noun + にもまさる", "Noun + にもまさるものはない"], "examples": [{"jp": "期待にもまさる結果だった。", "en": "The result exceeded expectations."}, {"jp": "この美しさにもまさるものはない。", "en": "Nothing surpasses this beauty."}], "notes": "Similar to にまさる, emphasizes surpassing something."},
    {"title": "～よりましだ", "meaning": "better than~, preferable to~", "level": "N3", "isImportant": False, "expressions": ["～よりましだ", "～よりまだましだ"], "patterns": ["Noun + よりましだ", "Noun + よりまだましだ"], "examples": [{"jp": "何もないよりましだ。", "en": "It's better than nothing."}, {"jp": "失敗するよりまだましだ。", "en": "It's still better than failing."}], "notes": "Expresses that something is at least better than an alternative."},
    {"title": "～というより", "meaning": "rather than~, more like~", "level": "N2", "isImportant": False, "expressions": ["～というより", "～というよりむしろ"], "patterns": ["Phrase + というより", "Phrase + というよりむしろ"], "examples": [{"jp": "彼は先生というより友人だ。", "en": "He is more a friend than a teacher."}, {"jp": "悲しいというより、怒っている。", "en": "Rather than sad, I'm angry."}], "notes": "Used to rephrase or correct a description."},
    {"title": "～よりむしろ", "meaning": "rather than~, more like~", "level": "N2", "isImportant": False, "expressions": ["～よりむしろ"], "patterns": ["Noun/Verb + よりむしろ"], "examples": [{"jp": "行くよりむしろ止めたい。", "en": "I'd rather stop than go."}, {"jp": "失敗するよりむしろ挑戦したい。", "en": "I'd rather try than fail."}], "notes": "Expresses preference for one option over another."},
    {"title": "～にこさる", "meaning": "to be inferior to~, to be worse than~", "level": "N1", "isImportant": False, "expressions": ["～にこさる", "～にこさるものはない"], "patterns": ["Noun + にこさる"], "examples": [{"jp": "品質にこさるものはない。", "en": "Nothing is inferior in quality."}, {"jp": "この味にこさるものはない。", "en": "Nothing is worse than this taste."}], "notes": "Rare, literary expression of inferiority."},
    {"title": "～に匹敵する", "meaning": "to match~, to be comparable to~, to rival~", "level": "N1", "isImportant": False, "expressions": ["～に匹敵する", "～に匹敵しない"], "patterns": ["Noun + に匹敵する"], "examples": [{"jp": "彼に匹敵する選手はいない。", "en": "There is no player who can match him."}, {"jp": "匹敵する性能を持つ。", "en": "Have comparable performance."}], "notes": "Expresses that something is on par with something else."},
    {"title": "～に凌ぐ", "meaning": "to surpass~, to outdo~, to excel over~", "level": "N1", "isImportant": False, "expressions": ["～に凌ぐ", "～を凌ぐ"], "patterns": ["Noun + に凌ぐ", "Noun + を凌ぐ"], "examples": [{"jp": "前人を凌ぐ業績を上げた。", "en": "Achieved results surpassing predecessors."}, {"jp": "競合を凌いで一位になる。", "en": "Outdo the competition and become number one."}], "notes": "Expresses surpassing or outperforming."},
    {"title": "～に優る", "meaning": "to be superior to~, to excel over~", "level": "N1", "isImportant": False, "expressions": ["～に優る", "～に優らない"], "patterns": ["Noun + に優る"], "examples": [{"jp": "彼に優る選手はいない。", "en": "There is no player superior to him."}, {"jp": "この品質に優るものはない。", "en": "Nothing is superior to this quality."}], "notes": "Formal/literary expression of superiority."},
    {"title": "～に劣る", "meaning": "to be inferior to~, to be worse than~", "level": "N1", "isImportant": False, "expressions": ["～に劣る", "～に劣らない"], "patterns": ["Noun + に劣る", "Noun + に劣らない"], "examples": [{"jp": "品質に劣る。", "en": "Be inferior in quality."}, {"jp": "彼に劣らない実力を持つ。", "en": "Have ability not inferior to his."}], "notes": "Expresses inferiority. ～に劣らない means 'not inferior to~'."},
    {"title": "～に等しい", "meaning": "equal to~, equivalent to~, as good as~", "level": "N1", "isImportant": False, "expressions": ["～に等しい", "～に等しく"], "patterns": ["Noun + に等しい"], "examples": [{"jp": "失敗に等しい結果だった。", "en": "The result was as good as a failure."}, {"jp": "彼の言葉は命令に等しい。", "en": "His words are equivalent to an order."}], "notes": "Expresses equivalence or something being practically the same."},
    {"title": "～に比肩する", "meaning": "to be on par with~, to match~, to rival~", "level": "N1", "isImportant": False, "expressions": ["～に比肩する", "～に比肩できない"], "patterns": ["Noun + に比肩する"], "examples": [{"jp": "彼に比肩する人はいない。", "en": "There is no one who can match him."}, {"jp": "比肩する実力を持つ。", "en": "Have matching ability."}], "notes": "Formal expression meaning to be equal to or comparable with."},
    {"title": "～に及ぶ", "meaning": "to reach~, to extend to~, to amount to~", "level": "N1", "isImportant": False, "expressions": ["～に及ぶ", "～に及ばない"], "patterns": ["Noun + に及ぶ"], "examples": [{"jp": "被害は甚大なものに及んだ。", "en": "The damage reached enormous proportions."}, {"jp": "影響は全国に及んでいる。", "en": "The influence extends nationwide."}], "notes": "Expresses reaching a certain scale or extent."},
    {"title": "～に至る", "meaning": "to reach~, to lead to~, to result in~", "level": "N1", "isImportant": False, "expressions": ["～に至る", "～に至らない"], "patterns": ["Noun + に至る"], "examples": [{"jp": "問題は深刻な段階に至った。", "en": "The problem has reached a serious stage."}, {"jp": "交渉は妥結に至った。", "en": "The negotiation reached a settlement."}], "notes": "Expresses reaching a certain state or result."},
    {"title": "～に至って", "meaning": "when it comes to~, at the point of~, upon~", "level": "N1", "isImportant": False, "expressions": ["～に至って", "～に至っても"], "patterns": ["Noun/Verb + に至って"], "examples": [{"jp": "問題が深刻化して至って、ようやく対策を取った。", "en": "When the problem became serious, measures were finally taken."}, {"jp": "失敗に至って、初めて気づいた。", "en": "Only when I failed did I realize."}], "notes": "Expresses reaching a point where something happens."},
    {"title": "～に至るまで", "meaning": "up to~, as far as~, even to the point of~", "level": "N1", "isImportant": False, "expressions": ["～に至るまで"], "patterns": ["Noun + に至るまで"], "examples": [{"jp": "準備から当日に至るまで、すべて計画通りだった。", "en": "From preparation to the day itself, everything went according to plan."}, {"jp": "細部に至るまで完璧だ。", "en": "It's perfect down to the details."}], "notes": "Expresses the full range or extent of something."},
    {"title": "～に基づいて", "meaning": "based on~, on the basis of~, according to~", "level": "N2", "isImportant": False, "expressions": ["～に基づいて", "～に基づき"], "patterns": ["Noun + に基づいて"], "examples": [{"jp": "データに基づいて判断する。", "en": "Judge based on data."}, {"jp": "法律に基づき処分する。", "en": "Punish according to the law."}], "notes": "Expresses the basis or foundation for something."},
    {"title": "～に沿って", "meaning": "along~, following~, in accordance with~", "level": "N2", "isImportant": False, "expressions": ["～に沿って", "～に沿い"], "patterns": ["Noun + に沿って"], "examples": [{"jp": "計画に沿って進める。", "en": "Proceed according to the plan."}, {"jp": "川に沿って歩く。", "en": "Walk along the river."}], "notes": "Expresses following a guideline, plan, or physical path."},
]

# ========== SCENES (10) ==========
scenes = [
    {"title": "スマートフォンを比較する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "新しいスマホを買いたいんだけど、何がいいかな？", "en": "I want to buy a new smartphone, but what's good?"}, {"speaker": "B", "jp": "何が一番重視する？カメラ？性能？", "en": "What do you value most? Camera? Performance?"}, {"speaker": "A", "jp": "カメラの性能がいいのがいいな。", "en": "I want one with good camera performance."}, {"speaker": "B", "jp": "このメリットとデメリットを比較してみたよ。", "en": "I compared the merits and demerits."}, {"speaker": "A", "jp": "ありがとう。これなら違いがはっきりわかる。", "en": "Thanks. Now I can clearly see the differences."}]},
    {"title": "大学を比較する", "level": "N2", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "どの大学に進学しようか迷っている。", "en": "I'm wondering which university to go to."}, {"speaker": "B", "jp": "それぞれの大学の特徴を調べた？", "en": "Have you looked into the characteristics of each university?"}, {"speaker": "A", "jp": "うん、A大学とB大学で迷ってる。", "en": "Yeah, I'm torn between University A and B."}, {"speaker": "B", "jp": "A大学は研究に、B大学は就職に強いよ。", "en": "University A is strong in research, B in job placement."}, {"speaker": "A", "jp": "そうなんだ。自分の優先順位を考えないと。", "en": "I see. I need to think about my priorities."}]},
    {"title": "レストランを比較する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "今日の昼ごはん、どこに行く？", "en": "Where are we going for lunch today?"}, {"speaker": "B", "jp": "あの新しいイタリアンはどう？", "en": "How about that new Italian place?"}, {"speaker": "A", "jp": "前に行ったことある？", "en": "Have you been there before?"}, {"speaker": "B", "jp": "いいえ、でもレビューがいいみたい。", "en": "No, but the reviews seem good."}, {"speaker": "A", "jp": "値段と味を比較して決めよう。", "en": "Let's compare price and taste to decide."}]},
    {"title": "仕事を比較する", "level": "N2", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "二つのオファーをもらって迷っている。", "en": "I got two offers and I'm torn."}, {"speaker": "B", "jp": "それぞれの条件を教えて。", "en": "Tell me the conditions of each."}, {"speaker": "A", "jp": "A社は給料が高いけど、残業が多い。", "en": "Company A has high salary but lots of overtime."}, {"speaker": "B", "jp": "B社は？", "en": "What about Company B?"}, {"speaker": "A", "jp": "給料は少し低いけど、ワークライフバランスがいい。", "en": "Salary is a bit lower, but work-life balance is good."}, {"speaker": "B", "jp": "メリットとデメリットをリストアップした方がいいよ。", "en": "You should list the merits and demerits."}]},
    {"title": "旅行先を比較する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "夏休みにどこに行きたい？", "en": "Where do you want to go for summer vacation?"}, {"speaker": "B", "jp": "ハワイとグアムで迷ってる。", "en": "I'm torn between Hawaii and Guam."}, {"speaker": "A", "jp": "それぞれの特徴は？", "en": "What are the characteristics of each?"}, {"speaker": "B", "jp": "ハワイは観光地が豊富だけど、高い。", "en": "Hawaii has many tourist spots, but it's expensive."}, {"speaker": "A", "jp": "グアムは近いし、値段も手頃だね。", "en": "Guam is close and the price is reasonable."}, {"speaker": "B", "jp": "予算と日程を比較して決めよう。", "en": "Let's compare budget and schedule to decide."}]},
    {"title": "賃貸マンションを比較する", "level": "N2", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "引っ越し先を探しているんだけど。", "en": "I'm looking for a new place to move to."}, {"speaker": "B", "jp": "どんな条件がある？", "en": "What conditions do you have?"}, {"speaker": "A", "jp": "家賃は8万以下で、駅から近いところ。", "en": "Rent under 80,000 yen, close to the station."}, {"speaker": "B", "jp": "この二つを比較してみた。", "en": "I compared these two."}, {"speaker": "A", "jp": "Aは家賃が安いけど、駅から遠いね。", "en": "A is cheap but far from the station."}, {"speaker": "B", "jp": "Bは駅から近いけど、少し高い。", "en": "B is close to the station but a bit expensive."}, {"speaker": "A", "jp": "優先順位をはっきりさせないと。", "en": "I need to clarify my priorities."}]},
    {"title": "車を比較する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "新しい車を買いたいんだけど。", "en": "I want to buy a new car."}, {"speaker": "B", "jp": "何を重視する？燃費？デザイン？", "en": "What do you value? Fuel efficiency? Design?"}, {"speaker": "A", "jp": "燃費がいいのがいいな。", "en": "I want one with good fuel efficiency."}, {"speaker": "B", "jp": "この二つの車を比較してみた。", "en": "I compared these two cars."}, {"speaker": "A", "jp": "Aは燃費がいいけど、値段が高いね。", "en": "A has good fuel efficiency but is expensive."}, {"speaker": "B", "jp": "Bは値段が手頃だけど、燃費が少し悪い。", "en": "B is reasonably priced but fuel efficiency is a bit bad."}, {"speaker": "A", "jp": "メリットとデメリットを考えてから決めよう。", "en": "Let's decide after considering the merits and demerits."}]},
    {"title": "保険を比較する", "level": "N2", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "生命保険に入りたいんだけど。", "en": "I want to get life insurance."}, {"speaker": "B", "jp": "どんな保障が欲しい？", "en": "What kind of coverage do you want?"}, {"speaker": "A", "jp": "病気の時の保障が欲しい。", "en": "I want coverage for when I get sick."}, {"speaker": "B", "jp": "この二つの保険を比較してみた。", "en": "I compared these two insurance plans."}, {"speaker": "A", "jp": "Aは保障が手厚いけど、保険料が高い。", "en": "A has generous coverage but high premiums."}, {"speaker": "B", "jp": "Bは保険料が安いけど、保障が少ない。", "en": "B has low premiums but less coverage."}, {"speaker": "A", "jp": "自分のニーズに合ったものを選ばないと。", "en": "I need to choose one that fits my needs."}]},
    {"title": "英語教室を比較する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "英語を習いたいんだけど、どの教室がいいかな？", "en": "I want to learn English, but which school is good?"}, {"speaker": "B", "jp": "何が一番重視する？会話？文法？", "en": "What do you value most? Conversation? Grammar?"}, {"speaker": "A", "jp": "会話ができるようになりたい。", "en": "I want to be able to have conversations."}, {"speaker": "B", "jp": "この二つの教室を比較してみた。", "en": "I compared these two schools."}, {"speaker": "A", "jp": "Aはネイティブ講師だけど、高いね。", "en": "A has native teachers but is expensive."}, {"speaker": "B", "jp": "Bは日本人講師だけど、安い。", "en": "B has Japanese teachers but is cheap."}, {"speaker": "A", "jp": "予算と目的を比較して決めよう。", "en": "Let's compare budget and purpose to decide."}]},
    {"title": "結婚式場を比較する", "level": "N2", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "結婚式場を探しているんだけど。", "en": "I'm looking for a wedding venue."}, {"speaker": "B", "jp": "どんな式がしたい？", "en": "What kind of ceremony do you want?"}, {"speaker": "A", "jp": "少人数で落ち着いた式がいいな。", "en": "I want a small, calm ceremony."}, {"speaker": "B", "jp": "この二つの式場を比較してみた。", "en": "I compared these two venues."}, {"speaker": "A", "jp": "Aは景色がいいけど、遠いね。", "en": "A has a nice view but is far."}, {"speaker": "B", "jp": "Bは駅から近いけど、少し騒がしい。", "en": "B is close to the station but a bit noisy."}, {"speaker": "A", "jp": "優先順位を決めてから訪問しよう。", "en": "Let's decide priorities and then visit."}]},
]

# ========== TOPICS (6) ==========
topics = [
    {"title": "比較の表現を使いこなす", "level": "N2", "body": "日本語には多くの比較表現があります。「～に比べて」「～よりも」「～というより」など、状況に応じて使い分ける必要があります。\n\n例えば、「この本はあの本に比べて面白い」は、二つの本を直接比較する表現です。「～に比べて」は、基準となるものを前に置き、その違いを述べる時に使います。\n\nまた、「～というより」は、直前の表現を訂正したり、より正確な表現に言い換えたりする時に使います。「彼は厳しいというより、真面目な人だ」という使い方です。\n\n比較表現をマスターすると、自分の意見をより正確に伝えられるようになります。", "questions": [{"question": "「～に比べて」の使い方として正しいのは？", "options": ["A. 基準を後に置く", "B. 基準を前に置く", "C. 比較しない", "D. 同じものを言う"], "answer": "B"}, {"question": "「～というより」は何をする表現？", "options": ["A. 強調する", "B. 訂正や言い換え", "C. 否定する", "D. 質問する"], "answer": "B"}]},
    {"title": "優劣を表す言葉の使い方", "level": "N1", "body": "日本語には優劣を表す言葉が豊富にあります。「優れる」「劣る」「勝る」「凌ぐ」など、それぞれ微妙に異なる意味を持っています。\n\n「優れる」は「他よりすぐれている」という意味で、「彼は語学に優れている」のように使います。「劣る」はその反対で、「品質に劣る」のように使います。\n\n「勝る」は「他よりまさっている」という意味で、「美しさでは彼女に勝る人はいない」のように使います。「凌ぐ」は「困難を乗り越える」という意味にもなりますが、「前人の業績を凌ぐ」のように「超える」という意味でも使います。\n\nこれらの言葉を正しく使い分けることで、より精密な表現が可能になります。", "questions": [{"question": "「優れる」の意味として正しいのは？", "options": ["A. 他より遅れている", "B. 他よりすぐれている", "C. 同じである", "D. 悪い"], "answer": "B"}, {"question": "「凌ぐ」の使い方として正しいのは？", "options": ["A. 困難を避ける", "B. 前人の業績を超える", "C. 同じレベルに保つ", "D. 劣る"], "answer": "B"}]},
    {"title": "選択と決断の表現", "level": "N2", "body": "日常生活で選択と決断をする場面は多くあります。日本語には、選択や決断を表す表現が多数あります。\n\n「二者択一」は「二つから一つを選ぶ」という意味で、「二者択一を迫られた」のように使います。「選り好み」は「好きなものを選ぶ」という意味で、「仕事は選り好みできない」のように使います。\n\n「決定的」は「これで決まる」という意味で、「決定的な証拠」のように使います。「優先」は「他より先にする」という意味で、「安全を優先する」のように使います。\n\nこれらの表現を学ぶことで、自分の意志を明確に伝えられるようになります。", "questions": [{"question": "「二者择一」の意味は？", "options": ["A. 三つから選ぶ", "B. 二つから一つを選ぶ", "C. 選ばない", "D. 全部選ぶ"], "answer": "B"}, {"question": "「優先」の使い方として正しいのは？", "options": ["A. 後回しにする", "B. 他より先にする", "C. 忘れる", "D. 避ける"], "answer": "B"}]},
    {"title": "商品の比較と選択", "level": "N3", "body": "買い物をするとき、商品を比較して選択する場面が多いです。日本語には、商品を比較する際に便利な表現があります。\n\n「メリットとデメリット」は「良い点と悪い点」という意味で、「メリットとデメリットを比較する」のように使います。「コストパフォーマンス」は「値段に見合った性能」という意味で、「コストパフォーマンスがいい」のように使います。\n\n「お買い得」は「安くて良い」という意味で、「お買い得な商品」のように使います。「セール」は「特別安売り」という意味で、「セール中の商品」のように使います。\n\n比較して賢く選ぶことで、満足度の高い買い物ができます。", "questions": [{"question": "「メリットとデメリット」の意味は？", "options": ["A. 高いと安い", "B. 良い点と悪い点", "C. 大きいと小さい", "D. 新しいと古い"], "answer": "B"}, {"question": "「コストパフォーマンス」の意味は？", "options": ["A. 値段が高い", "B. 値段に見合った性能", "C. 性能が悪い", "D. 値段が安い"], "answer": "B"}]},
    {"title": "都市と田舎の生活比較", "level": "N2", "body": "日本では都市と田舎の生活には大きな違いがあります。比較表現を使って、その違いを表現できます。\n\n都市の特徴は「便利」「交通の便がいい」「選択肢が多い」などです。一方、田舎の特徴は「自然が豊か」「静か」「コミュニティが密」などです。\n\n「都市に比べて、田舎は自然が豊かだ」「都市よりも田舎の方が静かだ」のように、比較表現を使って違いを明確にできます。\n\nどちらが優れているかは個人の価値観によります。重要なのは、自分の優先順位に合った選択をすることです。", "questions": [{"question": "都市の特徴として正しいのは？", "options": ["A. 自然が豊か", "B. 交通の便がいい", "C. 静か", "D. コミュニティが密"], "answer": "B"}, {"question": "比較表現の使い方として正しいのは？", "options": ["A. 違いを曖昧にする", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
    {"title": "日本の交通機関の比較", "level": "N2", "body": "日本には多くの交通機関があります。それぞれ特徴が異なり、比較して選ぶ必要があります。\n\n電車は「速い」「定時運行」「混雑」が特徴です。バスは「料金が安い」「路線が多い」「渋滞に影響を受ける」が特徴です。車は「自由度が高い」「駐車代が高い」「渋滞に影響を受ける」が特徴です。飛行機は「遠くに速い」「料金が高い」「空港へのアクセスが必要」が特徴です。\n\n「電車に比べて、バスは安いけど遅い」「車よりも電車の方が環境に優しい」のように、比較表現を使って交通機関を評価できます。\n\n目的地や予算に応じて、最適な交通機関を選びましょう。", "questions": [{"question": "電車の特徴として正しいのは？", "options": ["A. 料金が安い", "B. 定時運行", "C. 渋滞に影響を受ける", "D. 自由度が高い"], "answer": "B"}, {"question": "比較表現の目的は？", "options": ["A. 違いを隠す", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
]

# ========== Write files ==========
def write_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

write_json(DATA_DIR / "new_words.json", words)
write_json(DATA_DIR / "new_grammar.json", grammar)
write_json(DATA_DIR / "new_scenes.json", scenes)
write_json(DATA_DIR / "new_topics.json", topics)

print(f"Generated: {len(words)} words, {len(grammar)} grammar, {len(scenes)} scenes, {len(topics)} topics")
