#!/usr/bin/env python3
"""Generate remaining JLPT data for topic: 比较（优劣、异同、选择）"""
import json
from pathlib import Path

DATA_DIR = Path.home() / "OneDrive" / "ドキュメント" / "apex" / "japanese-data"

# ========== WORDS (11) ==========
words = [
    {"word": "隔てる", "reading": "へだてる", "meaning": "to separate, to partition, to create distance", "level": "N2", "isImportant": False, "examples": [{"jp": "二人の間に壁を隔てる。", "en": "Put a wall between the two people."}, {"jp": "文化の違いを隔てる壁。", "en": "A wall separating cultural differences."}]},
    {"word": "均等", "reading": "きんとう", "meaning": "equal, even, uniform", "level": "N2", "isImportant": False, "examples": [{"jp": "均等に分配する。", "en": "Distribute equally."}, {"jp": "均等な機会を与える。", "en": "Give equal opportunities."}]},
    {"word": "釣り合う", "reading": "つりあう", "meaning": "to balance, to match, to be in harmony", "level": "N3", "isImportant": False, "examples": [{"jp": "収入と支出が釣り合っている。", "en": "Income and expenses are balanced."}, {"jp": "色が釣り合った服。", "en": "Clothes with matching colors."}]},
    {"word": "均衡", "reading": "きんこう", "meaning": "equilibrium, balance, equalization", "level": "N1", "isImportant": False, "examples": [{"jp": "力の均衡を保つ。", "en": "Maintain a balance of power."}, {"jp": "均衡が崩れた。", "en": "The balance collapsed."}]},
    {"word": "不平等", "reading": "ふびょうどう", "meaning": "inequality, unfairness, disparity", "level": "N2", "isImportant": False, "examples": [{"jp": "不平等な扱いを受ける。", "en": "Receive unequal treatment."}, {"jp": "不平等を解消する。", "en": "Eliminate inequality."}]},
    {"word": "対比", "reading": "たいひ", "meaning": "contrast, comparison, antithesis", "level": "N2", "isImportant": False, "examples": [{"jp": "明暗の対比が美しい。", "en": "The contrast of light and dark is beautiful."}, {"jp": "対比する色を選ぶ。", "en": "Choose contrasting colors."}]},
    {"word": "対照", "reading": "たいしょう", "meaning": "contrast, comparison, antithesis", "level": "N2", "isImportant": False, "examples": [{"jp": "対照的な性格の二人。", "en": "Two people with contrasting personalities."}, {"jp": "表を作成して対照する。", "en": "Create a table to compare."}]},
    {"word": "比較対象", "reading": "ひかくたいしょう", "meaning": "object of comparison, comparator", "level": "N2", "isImportant": False, "examples": [{"jp": "比較対象を明確にする。", "en": "Clarify the object of comparison."}, {"jp": "比較対象外の項目。", "en": "Items outside the comparison."}]},
    {"word": "比較可能性", "reading": "ひかくかのうせい", "meaning": "comparability", "level": "N1", "isImportant": False, "examples": [{"jp": "比較可能性を高める。", "en": "Increase comparability."}, {"jp": "比較可能性がない。", "en": "There is no comparability."}]},
    {"word": "優位性", "reading": "ゆういせい", "meaning": "superiority, dominance, advantage", "level": "N1", "isImportant": False, "examples": [{"jp": "優位性を保つ。", "en": "Maintain superiority."}, {"jp": "優位性がある。", "en": "There is an advantage."}]},
    {"word": "劣勢", "reading": "れっせい", "meaning": "inferiority, disadvantage, adverse situation", "level": "N1", "isImportant": False, "examples": [{"jp": "劣勢に立つ。", "en": "Be in an inferior position."}, {"jp": "劣勢を挽回する。", "en": "Recover from the disadvantage."}]},
]

# ========== GRAMMAR (8) ==========
grammar = [
    {"title": "～に基づく", "meaning": "based on~, on the basis of~, grounded in~", "level": "N2", "isImportant": False, "expressions": ["～に基づく", "～に基づいた"], "patterns": ["Noun + に基づく", "Noun + に基づいた + Noun"], "examples": [{"jp": "事実に基づく判断。", "en": "Judgment based on facts."}, {"jp": "法律に基づく処分。", "en": "Punishment based on law."}], "notes": "Same meaning as に基づいて, but used as an adjective."},
    {"title": "～に沿う", "meaning": "to follow~, to comply with~, to be along~", "level": "N2", "isImportant": False, "expressions": ["～に沿う", "～に沿った"], "patterns": ["Noun + に沿う", "Noun + に沿った + Noun"], "examples": [{"jp": "計画に沿って進める。", "en": "Proceed along the plan."}, {"jp": "方針に沿った行動。", "en": "Action following the policy."}], "notes": "Can be used as an adjective with に沿った."},
    {"title": "～にわたる", "meaning": "over~, across~, throughout~, spanning~", "level": "N2", "isImportant": False, "expressions": ["～にわたる", "～にわたって"], "patterns": ["Noun + にわたる", "Noun + にわたって"], "examples": [{"jp": "全国にわたる調査。", "en": "A survey spanning the whole country."}, {"jp": "長年にわたる研究。", "en": "Research spanning many years."}], "notes": "Expresses a wide range or long period."},
    {"title": "～を中心に", "meaning": "centered around~, focusing on~, mainly~", "level": "N2", "isImportant": False, "expressions": ["～を中心に", "～を中心として"], "patterns": ["Noun + を中心に"], "examples": [{"jp": "東京を中心に活動する。", "en": "Be active mainly in Tokyo."}, {"jp": "若者を中心に人気がある。", "en": "Popular mainly among young people."}], "notes": "Expresses the center or main focus."},
    {"title": "～を通じて", "meaning": "through~, via~, over the period of~", "level": "N2", "isImportant": False, "expressions": ["～を通じて", "～を通して"], "patterns": ["Noun + を通じて"], "examples": [{"jp": "友人を通じて知った。", "en": "I learned about it through a friend."}, {"jp": "一年を通じて温暖だ。", "en": "It's warm throughout the year."}], "notes": "Expresses a medium or a period of time."},
    {"title": "～に伴う", "meaning": "accompanying~, along with~, associated with~", "level": "N2", "isImportant": False, "expressions": ["～に伴う", "～に伴って"], "patterns": ["Noun + に伴う", "Noun + に伴って"], "examples": [{"jp": "人口増加に伴う問題。", "en": "Problems accompanying population growth."}, {"jp": "変化に伴うリスク。", "en": "Risks associated with change."}], "notes": "Expresses something that accompanies or results from something."},
    {"title": "～に応じる", "meaning": "to respond to~, to meet (demand/wishes), to accommodate~", "level": "N2", "isImportant": False, "expressions": ["～に応じる", "～に応じて"], "patterns": ["Noun + に応じる", "Noun + に応じて"], "examples": [{"jp": "需要に応じる。", "en": "Respond to demand."}, {"jp": "能力に応じて給料が決まる。", "en": "Salary is determined according to ability."}], "notes": "Expresses responding or adapting to something."},
    {"title": "～に即す", "meaning": "to follow~, to be based on~, to be true to~", "level": "N1", "isImportant": False, "expressions": ["～に即す", "～に即して"], "patterns": ["Noun + に即す", "Noun + に即して"], "examples": [{"jp": "現状に即して判断する。", "en": "Judge based on the current situation."}, {"jp": "事実に即した話。", "en": "A story based on facts."}], "notes": "Expresses being based on reality or actual conditions."},
]

# ========== SCENES (10) ==========
scenes = [
    {"title": "カフェで友達と話す", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "この前、新しいカフェに行った？", "en": "Did you go to the new cafe the other day?"}, {"speaker": "B", "jp": "うん、雰囲気は良かったけど、コーヒーは普通だった。", "en": "Yeah, the atmosphere was good but the coffee was average."}, {"speaker": "A", "jp": "この前のカフェと比べてどう？", "en": "How does it compare to the last cafe?"}, {"speaker": "B", "jp": "こちらの方が落ち着くね。", "en": "This one is more relaxing."}, {"speaker": "A", "jp": "じゃあ、次はそこに行こう。", "en": "Then let's go there next time."}]},
    {"title": "本を選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "何か面白い本はないかな？", "en": "I wonder if there are any interesting books?"}, {"speaker": "B", "jp": "この小説はどう？評価が高いよ。", "en": "How about this novel? It has high ratings."}, {"speaker": "A", "jp": "前に読んだことある？", "en": "Have you read it before?"}, {"speaker": "B", "jp": "いいえ、でもレビューがいいみたい。", "en": "No, but the reviews seem good."}, {"speaker": "A", "jp": "値段と内容を比較して決めよう。", "en": "Let's compare price and content to decide."}]},
    {"title": "服を選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "この服、どう？", "en": "How about this outfit?"}, {"speaker": "B", "jp": "いいと思うけど、高いね。", "en": "I think it's nice, but it's expensive."}, {"speaker": "A", "jp": "前に買ったのと比べてどう？", "en": "How does it compare to what you bought before?"}, {"speaker": "B", "jp": "こちらの方が品質がいいね。", "en": "This one has better quality."}, {"speaker": "A", "jp": "メリットとデメリットを考えてから決めよう。", "en": "Let's decide after considering the merits and demerits."}]},
    {"title": "映画を選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "今日の映画、何を見る？", "en": "What movie are we watching today?"}, {"speaker": "B", "jp": "アクションとラブロマンスで迷ってる。", "en": "I'm torn between action and romance."}, {"speaker": "A", "jp": "どっちがいいかな？", "en": "Which one is better?"}, {"speaker": "B", "jp": "アクションは面白いけど、ラブロマンスは感動的だよ。", "en": "Action is fun, but romance is moving."}, {"speaker": "A", "jp": "気分で選ぼう。", "en": "Let's choose based on our mood."}]},
    {"title": "スポーツクラブを選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "スポーツクラブに入りたいんだけど。", "en": "I want to join a sports club."}, {"speaker": "B", "jp": "何がしたい？", "en": "What do you want to do?"}, {"speaker": "A", "jp": "水泳とテニスで迷ってる。", "en": "I'm torn between swimming and tennis."}, {"speaker": "B", "jp": "水泳は全身運動だよ。", "en": "Swimming is a full-body workout."}, {"speaker": "A", "jp": "テニスは技術が必要だね。", "en": "Tennis requires skill."}, {"speaker": "B", "jp": "体験してから決めればいいよ。", "en": "You can try it and then decide."}]},
    {"title": "デパートで買い物", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "プレゼントを選んでるんだけど。", "en": "I'm choosing a present."}, {"speaker": "B", "jp": "誰へのプレゼント？", "en": "A present for whom?"}, {"speaker": "A", "jp": "母へのプレゼント。", "en": "A present for my mother."}, {"speaker": "B", "jp": "このスカーフはどう？", "en": "How about this scarf?"}, {"speaker": "A", "jp": "前に買ったのと比べて品質がいいね。", "en": "The quality is better compared to what I bought before."}, {"speaker": "B", "jp": "色もきれいだよ。", "en": "The color is beautiful too."}]},
    {"title": "スーパーで食材を選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "今晚の夕食、何を作る？", "en": "What are you making for dinner tonight?"}, {"speaker": "B", "jp": "肉と魚で迷ってる。", "en": "I'm torn between meat and fish."}, {"speaker": "A", "jp": "どっちが安い？", "en": "Which is cheaper?"}, {"speaker": "B", "jp": "魚の方が少し高いけど、健康的だよ。", "en": "Fish is a bit more expensive, but it's healthy."}, {"speaker": "A", "jp": "健康には変えられないね。", "en": "Nothing can replace health."}, {"speaker": "B", "jp": "じゃあ、魚にしよう。", "en": "Then let's go with fish."}]},
    {"title": "音楽を聴く", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "最近何の音楽を聴いてる？", "en": "What music have you been listening to lately?"}, {"speaker": "B", "jp": "J-POPと洋楽で迷ってる。", "en": "I'm torn between J-POP and Western music."}, {"speaker": "A", "jp": "どっちが好き？", "en": "Which do you like better?"}, {"speaker": "B", "jp": "J-POPは歌詞がわかるけど、洋楽はリズムがいい。", "en": "I understand the lyrics in J-POP, but Western music has good rhythm."}, {"speaker": "A", "jp": "両方聴けばいいじゃない。", "en": "Why not listen to both?"}]},
    {"title": "旅行の相談", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "来年の旅行、どこに行きたい？", "en": "Where do you want to go for next year's trip?"}, {"speaker": "B", "jp": "ヨーロッパとアメリカで迷ってる。", "en": "I'm torn between Europe and America."}, {"speaker": "A", "jp": "それぞれの特徴は？", "en": "What are the characteristics of each?"}, {"speaker": "B", "jp": "ヨーロッパは歴史が深いけど、お金がかかる。", "en": "Europe has deep history, but it costs money."}, {"speaker": "A", "jp": "アメリカは広いけど、移動が大変。", "en": "America is big, but getting around is tough."}, {"speaker": "B", "jp": "予算と日程を比較して決めよう。", "en": "Let's compare budget and schedule to decide."}]},
    {"title": "アルバイトを選ぶ", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "A", "jp": "アルバイトを探してるんだけど。", "en": "I'm looking for a part-time job."}, {"speaker": "B", "jp": "どんな仕事がしたい？", "en": "What kind of work do you want to do?"}, {"speaker": "A", "jp": "カフェとコンビニで迷ってる。", "en": "I'm torn between a cafe and a convenience store."}, {"speaker": "B", "jp": "カフェは楽しいけど、忙しいよ。", "en": "Cafe is fun, but busy."}, {"speaker": "A", "jp": "コンビニは簡単だけど、つまらない。", "en": "Convenience store is easy, but boring."}, {"speaker": "B", "jp": "自分に合った方を選んだ方がいいよ。", "en": "You should choose the one that suits you."}]},
]

# ========== TOPICS (4) ==========
topics = [
    {"title": "日本の医療制度と他国の比較", "level": "N2", "body": "日本の医療制度は世界的に見ても高い水準にあります。しかし、他国と比較すると異なる点もあります。\n\n日本は国民健康保険制度で、全員が保険に加入しています。医療費の自己負担は割合で決まり、高齢者は負担が軽減されます。一方、アメリカは民間保険が中心で、保険未加入者も多くいます。\n\n「日本に比べて、アメリカの医療費は高い」「日本よりもスウェーデンの方が待ち時間が短い」のように、比較表現を使って医療制度を評価できます。\n\nそれぞれの制度にメリットとデメリットがあり、一概にどれが優れているとは言えません。", "questions": [{"question": "日本の医療制度の特徴は？", "options": ["A. 民間保険が中心", "B. 国民健康保険制度", "C. 自己負担なし", "D. 高齢者のみ加入"], "answer": "B"}, {"question": "比較表現の使い方として正しいのは？", "options": ["A. 違いを隠す", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
    {"title": "日本の教育制度と他国の比較", "level": "N2", "body": "日本の教育制度は6・3・3制で、小学校6年、中学校3年、高校3年です。他国と比較すると、異なる点があります。\n\n日本は詰め込み教育と言われますが、最近はアクティブラーニングも導入されています。アメリカは討論を重視し、フィンランドは個性を重視しています。\n\n「日本に比べて、アメリカは討論が多い」「日本よりもフィンランドの方が個性を重視している」のように、比較表現を使って教育制度を評価できます。\n\nそれぞれの制度にメリットとデメリットがあり、重要なのは子どもたちの成長に合った教育を選ぶことです。", "questions": [{"question": "日本の教育制度の特徴は？", "options": ["A. 討論を重視", "B. 6・3・3制", "C. 個性を重視", "D. 詰め込みのみ"], "answer": "B"}, {"question": "比較表現の目的は？", "options": ["A. 違いを隠す", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
    {"title": "就職先の選び方と比較", "level": "N2", "body": "就職活動では、複数の企業を比較して選ぶことが大切です。比較する際のポイントを紹介します。\n\nまず、給料と福利厚生を比較します。次に、働き方とワークライフバランスを比較します。そして、企業文化と成長機会を比較します。\n\n「A社に比べて、B社は給料が高い」「A社よりもC社の方がワークライフバランスがいい」のように、比較表現を使って企業を評価できます。\n\nメリットとデメリットをリストアップし、自分の優先順位に合った企業を選びましょう。", "questions": [{"question": "就職先を比較する際のポイントは？", "options": ["A. 給料のみ", "B. 福利厚生のみ", "C. 給料、働き方、企業文化など", "D. 企業文化のみ"], "answer": "C"}, {"question": "比較表現の使い方として正しいのは？", "options": ["A. 違いを隠す", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
    {"title": "日本の交通機関の比較", "level": "N2", "body": "日本には多くの交通機関があります。それぞれ特徴が異なり、比較して選ぶ必要があります。\n\n電車は「速い」「定時運行」「混雑」が特徴です。バスは「料金が安い」「路線が多い」「渋滞に影響を受ける」が特徴です。車は「自由度が高い」「駐車代が高い」「渋滞に影響を受ける」が特徴です。飛行機は「遠くに速い」「料金が高い」「空港へのアクセスが必要」が特徴です。\n\n「電車に比べて、バスは安いけど遅い」「車よりも電車の方が環境に優しい」のように、比較表現を使って交通機関を評価できます。\n\n目的地や予算に応じて、最適な交通機関を選びましょう。", "questions": [{"question": "電車の特徴として正しいのは？", "options": ["A. 料金が安い", "B. 定時運行", "C. 渋滞に影響を受ける", "D. 自由度が高い"], "answer": "B"}, {"question": "比較表現の目的は？", "options": ["A. 違いを隠す", "B. 違いを明確にする", "C. 同じことを言う", "D. 避ける"], "answer": "B"}]},
]

# ========== Write files ==========
def write_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

write_json(DATA_DIR / "new_words.json", words)
write_json(DATA_DIR / "new_grammar.json", grammar)
write_json(DATA_DIR / "new_scenes.json", scenes)
write_json(DATA_DIR / "new_topics.json", topics)

print(f"Generated: {len(words)} words, {len(grammar)} grammar, {len(scenes)} scenes, {len(topics)} topics")
