#!/usr/bin/env python3
"""Generate today's JLPT data for topic: 留学（申请、签证、住宿）"""
import json
from pathlib import Path

DATA_DIR = Path.home() / "OneDrive" / "ドキュメント" / "apex" / "japanese-data"

# ========== WORDS (40) ==========
words = [
    {"word": "留学", "reading": "りゅうがく", "meaning": "studying abroad", "level": "N3", "isImportant": False, "examples": [{"jp": "アメリカに留学する。", "en": "Study abroad in America."}, {"jp": "留学経験がある。", "en": "I have study abroad experience."}]},
    {"word": "入国", "reading": "にゅうこく", "meaning": "entry into a country, immigration", "level": "N2", "isImportant": False, "examples": [{"jp": "入国審査を受ける。", "en": "Go through immigration."}, {"jp": "入国ビザが必要だ。", "en": "An entry visa is required."}]},
    {"word": "出国", "reading": "しゅっこく", "meaning": "departure from a country", "level": "N2", "isImportant": False, "examples": [{"jp": "出国手続きをする。", "en": "Complete departure procedures."}, {"jp": "出国カードを提出する。", "en": "Submit the departure card."}]},
    {"word": "ビザ", "reading": "びざ", "meaning": "visa", "level": "N3", "isImportant": False, "examples": [{"jp": "ビザを申請する。", "en": "Apply for a visa."}, {"jp": "ビザが切れた。", "en": "The visa expired."}]},
    {"word": "パスポート", "reading": "ぱすぽーと", "meaning": "passport", "level": "N4", "isImportant": False, "examples": [{"jp": "パスポートを提示する。", "en": "Present your passport."}, {"jp": "パスポートの更新をする。", "en": "Renew your passport."}]},
    {"word": "滞在", "reading": "たいざい", "meaning": "stay, residence", "level": "N2", "isImportant": False, "examples": [{"jp": "長期滞在する。", "en": "Stay for a long period."}, {"jp": "滞在期間を延長する。", "en": "Extend the period of stay."}]},
    {"word": "在留", "reading": "ざいりゅう", "meaning": "residence, staying in a country", "level": "N1", "isImportant": False, "examples": [{"jp": "在留資格を取る。", "en": "Obtain residence status."}, {"jp": "在留カードを持っている。", "en": "I have a residence card."}]},
    {"word": "宿泊", "reading": "しゅくはく", "meaning": "lodging, accommodation", "level": "N2", "isImportant": False, "examples": [{"jp": "宿泊施設を予約する。", "en": "Book accommodation."}, {"jp": "宿泊費が高い。", "en": "Accommodation costs are high."}]},
    {"word": "下宿", "reading": "げしゅく", "meaning": "boarding house, lodging", "level": "N2", "isImportant": False, "examples": [{"jp": "下宿を探す。", "en": "Look for a boarding house."}, {"jp": "下宿代を払う。", "en": "Pay boarding fees."}]},
    {"word": "寮", "reading": "りょう", "meaning": "dormitory, residence hall", "level": "N3", "isImportant": False, "examples": [{"jp": "学生寮に入る。", "en": "Enter a student dormitory."}, {"jp": "寮の規則を守る。", "en": "Follow dormitory rules."}]},
    {"word": "アパート", "reading": "あぱーと", "meaning": "apartment, flat", "level": "N4", "isImportant": False, "examples": [{"jp": "アパートを借りる。", "en": "Rent an apartment."}, {"jp": "アパートの家賃が高い。", "en": "Apartment rent is expensive."}]},
    {"word": "契約", "reading": "けいやく", "meaning": "contract, agreement", "level": "N2", "isImportant": False, "examples": [{"jp": "契約を結ぶ。", "en": "Conclude a contract."}, {"jp": "契約書にサインする。", "en": "Sign the contract."}]},
    {"word": "申込", "reading": "もうしこみ", "meaning": "application, subscription", "level": "N2", "isImportant": False, "examples": [{"jp": "申込書を提出する。", "en": "Submit an application form."}, {"jp": "申込期限が迫っている。", "en": "The application deadline is approaching."}]},
    {"word": "手続き", "reading": "てつづき", "meaning": "procedure, formalities", "level": "N3", "isImportant": False, "examples": [{"jp": "手続きが面倒だ。", "en": "The procedure is troublesome."}, {"jp": "手続きを済ませる。", "en": "Complete the procedure."}]},
    {"word": "書類", "reading": "しょるい", "meaning": "documents, papers", "level": "N3", "isImportant": False, "examples": [{"jp": "書類を準備する。", "en": "Prepare documents."}, {"jp": "書類審査がある。", "en": "There is a document review."}]},
    {"word": "証明", "reading": "しょうめい", "meaning": "proof, certificate, verification", "level": "N2", "isImportant": False, "examples": [{"jp": "証明書を提出する。", "en": "Submit a certificate."}, {"jp": "身分証明書が必要だ。", "en": "ID is required."}]},
    {"word": "推薦", "reading": "すいせん", "meaning": "recommendation", "level": "N2", "isImportant": False, "examples": [{"jp": "先生の推薦をもらう。", "en": "Get a recommendation from a teacher."}, {"jp": "推薦状を書く。", "en": "Write a recommendation letter."}]},
    {"word": "面接", "reading": "めんせつ", "meaning": "interview", "level": "N2", "isImportant": False, "examples": [{"jp": "面接を受ける。", "en": "Have an interview."}, {"jp": "面接官に聞かれる。", "en": "Be asked by the interviewer."}]},
    {"word": "合格", "reading": "ごうかく", "meaning": "pass, success", "level": "N3", "isImportant": False, "examples": [{"jp": "試験に合格する。", "en": "Pass the exam."}, {"jp": "合格通知が来た。", "en": "A pass notification came."}]},
    {"word": "入学", "reading": "にゅうがく", "meaning": "entrance, admission", "level": "N3", "isImportant": False, "examples": [{"jp": "大学に入学する。", "en": "Enter university."}, {"jp": "入学式に出席する。", "en": "Attend the entrance ceremony."}]},
    {"word": "卒業", "reading": "そつぎょう", "meaning": "graduation", "level": "N3", "isImportant": False, "examples": [{"jp": "大学を卒業する。", "en": "Graduate from university."}, {"jp": "卒業論文を書く。", "en": "Write a graduation thesis."}]},
    {"word": "進学", "reading": "しんがく", "meaning": "advancing to a higher school", "level": "N2", "isImportant": False, "examples": [{"jp": "大学に進学する。", "en": "Go on to university."}, {"jp": "進学を目指す。", "en": "Aim to go on to higher education."}]},
    {"word": "専門", "reading": "せんもん", "meaning": "specialty, field of study", "level": "N3", "isImportant": False, "examples": [{"jp": "専門を選ぶ。", "en": "Choose a specialty."}, {"jp": "専門分野を学ぶ。", "en": "Study a specialized field."}]},
    {"word": "授業", "reading": "じゅぎょう", "meaning": "class, lesson", "level": "N3", "isImportant": False, "examples": [{"jp": "授業に出る。", "en": "Attend class."}, {"jp": "授業料を払う。", "en": "Pay tuition fees."}]},
    {"word": "単位", "reading": "たんい", "meaning": "credit, unit", "level": "N2", "isImportant": False, "examples": [{"jp": "単位を取る。", "en": "Earn credits."}, {"jp": "単位が足りない。", "en": "I don't have enough credits."}]},
    {"word": "奨学金", "reading": "しょうがくきん", "meaning": "scholarship", "level": "N2", "isImportant": False, "examples": [{"jp": "奨学金をもらう。", "en": "Receive a scholarship."}, {"jp": "奨学金を申請する。", "en": "Apply for a scholarship."}]},
    {"word": "生活費", "reading": "せいひつひ", "meaning": "living expenses, cost of living", "level": "N3", "isImportant": False, "examples": [{"jp": "生活費を稼ぐ。", "en": "Earn living expenses."}, {"jp": "生活費が高い。", "en": "The cost of living is high."}]},
    {"word": "家賃", "reading": "やちん", "meaning": "rent, house rent", "level": "N3", "isImportant": False, "examples": [{"jp": "家賃を払う。", "en": "Pay rent."}, {"jp": "家賃が安い。", "en": "The rent is cheap."}]},
    {"word": "光熱費", "reading": "こうねつひ", "meaning": "utility costs, electricity and gas bills", "level": "N2", "isImportant": False, "examples": [{"jp": "光熱費を節約する。", "en": "Save on utility costs."}, {"jp": "光熱費が高い。", "en": "Utility costs are high."}]},
    {"word": "食費", "reading": "しょくひ", "meaning": "food expenses", "level": "N3", "isImportant": False, "examples": [{"jp": "食費を抑える。", "en": "Hold down food expenses."}, {"jp": "食費がかさむ。", "en": "Food expenses increase."}]},
    {"word": "交通費", "reading": "こうつうひ", "meaning": "transportation cost", "level": "N3", "isImportant": False, "examples": [{"jp": "交通費がかかる。", "en": "Transportation costs money."}, {"jp": "交通費を節約する。", "en": "Save on transportation costs."}]},
    {"word": "保険", "reading": "ほけん", "meaning": "insurance", "level": "N3", "isImportant": False, "examples": [{"jp": "保険に入る。", "en": "Get insurance."}, {"jp": "保険料を払う。", "en": "Pay insurance premiums."}]},
    {"word": "病院", "reading": "びょういん", "meaning": "hospital", "level": "N4", "isImportant": False, "examples": [{"jp": "病院に行く。", "en": "Go to the hospital."}, {"jp": "病院で診察を受ける。", "en": "Be examined at the hospital."}]},
    {"word": "薬", "reading": "くすり", "meaning": "medicine, drug", "level": "N4", "isImportant": False, "examples": [{"jp": "薬を飲む。", "en": "Take medicine."}, {"jp": "薬をもらう。", "en": "Get medicine."}]},
    {"word": "病気", "reading": "びょうき", "meaning": "illness, sickness", "level": "N4", "isImportant": False, "examples": [{"jp": "病気になる。", "en": "Get sick."}, {"jp": "病気が治る。", "en": "The illness is cured."}]},
    {"word": "怪我", "reading": "けが", "meaning": "injury, wound", "level": "N4", "isImportant": False, "examples": [{"jp": "怪我をする。", "en": "Get injured."}, {"jp": "怪我が治る。", "en": "The injury heals."}]},
    {"word": "緊急", "reading": "きんきゅう", "meaning": "emergency, urgency", "level": "N2", "isImportant": False, "examples": [{"jp": "緊急事態だ。", "en": "It's an emergency."}, {"jp": "緊急連絡先を教える。", "en": "Tell me your emergency contact."}]},
    {"word": "警察", "reading": "けいさつ", "meaning": "police", "level": "N4", "isImportant": False, "examples": [{"jp": "警察に連絡する。", "en": "Contact the police."}, {"jp": "警察に行く。", "en": "Go to the police."}]},
    {"word": "盗難", "reading": "とうなん", "meaning": "theft, robbery", "level": "N2", "isImportant": False, "examples": [{"jp": "盗難に遭う。", "en": "Be robbed."}, {"jp": "盗難届を出す。", "en": "File a theft report."}]},
    {"word": "事故", "reading": "じこ", "meaning": "accident", "level": "N3", "isImportant": False, "examples": [{"jp": "事故が起きる。", "en": "An accident occurs."}, {"jp": "事故に遭う。", "en": "Be in an accident."}]},
    {"word": "忘れ物", "reading": "わすれもの", "meaning": "lost item, forgotten item", "level": "N3", "isImportant": False, "examples": [{"jp": "忘れ物をする。", "en": "Leave something behind."}, {"jp": "忘れ物を届ける。", "en": "Turn in a lost item."}]},
]

# ========== GRAMMAR (20) ==========
grammar = [
    {"title": "～ために", "meaning": "for the purpose of~, in order to~, for~", "level": "N3", "isImportant": False, "expressions": ["～ために", "～ための"], "patterns": ["Verb + ために", "Noun + のために", "Verb + ための + Noun"], "examples": [{"jp": "留学するために貯金する。", "en": "Save money to study abroad."}, {"jp": "留学ための資金を集める。", "en": "Raise funds for studying abroad."}], "notes": "Expresses purpose or reason."},
    {"title": "～ようにする", "meaning": "to make sure to~, to try to~, to make an effort to~", "level": "N3", "isImportant": False, "expressions": ["～ようにする", "～ようにしている"], "patterns": ["Verb + ようにする", "Verb + ようにしている"], "examples": [{"jp": "毎日勉強するようにしている。", "en": "I make sure to study every day."}, {"jp": "早く寝るようにする。", "en": "I try to sleep early."}], "notes": "Expresses effort or intention."},
    {"title": "～ことにする", "meaning": "to decide to~, to make up one's mind to~", "level": "N3", "isImportant": False, "expressions": ["～ことにする", "～ことにした"], "patterns": ["Verb + ことにする", "Verb + ことにした"], "examples": [{"jp": "留学することにした。", "en": "I decided to study abroad."}, {"jp": "毎日運動することにする。", "en": "I decide to exercise every day."}], "notes": "Expresses a decision."},
    {"title": "～ことになる", "meaning": "it has been decided that~, it turns out that~", "level": "N3", "isImportant": False, "expressions": ["～ことになる", "～ことになった"], "patterns": ["Verb + ことになる", "Verb + ことになった"], "examples": [{"jp": "来月留学することになった。", "en": "It was decided that I will study abroad next month."}, {"jp": "日本に行くことになった。", "en": "It turned out I'm going to Japan."}], "notes": "Expresses a decision made by others or circumstances."},
    {"title": "～ように言う", "meaning": "to tell (someone) to~, to advise to~", "level": "N3", "isImportant": False, "expressions": ["～ように言う", "～ように言われた"], "patterns": ["Person + に + Verb + ように言う", "Person + に + Verb + ように言われた"], "examples": [{"jp": "先生が早く寝るように言った。", "en": "The teacher told me to sleep early."}, {"jp": "医者に運動するように言われた。", "en": "The doctor told me to exercise."}], "notes": "Expresses being told or advised to do something."},
    {"title": "～ように注意する", "meaning": "to be careful to~, to warn to~", "level": "N3", "isImportant": False, "expressions": ["～ように注意する", "～ように注意された"], "patterns": ["Person + に + Verb + ように注意する", "Person + に + Verb + ように注意された"], "examples": [{"jp": "遅刻しないように注意する。", "en": "Be careful not to be late."}, {"jp": "病気にならないように注意された。", "en": "I was warned to be careful not to get sick."}], "notes": "Expresses caution or warning."},
    {"title": "～ばよかった", "meaning": "I wish I had~, I should have~", "level": "N3", "isImportant": False, "expressions": ["～ばよかった", "～なければよかった"], "patterns": ["Verb + ばよかった", "Verb + なければよかった"], "examples": [{"jp": "もっと早く申請すればよかった。", "en": "I wish I had applied earlier."}, {"jp": "保険に入ればよかった。", "en": "I wish I had gotten insurance."}], "notes": "Expresses regret about the past."},
    {"title": "～ておく", "meaning": "to do in advance, to do for later", "level": "N3", "isImportant": False, "expressions": ["～ておく", "～ておいた"], "patterns": ["Verb + ておく", "Verb + ておいた"], "examples": [{"jp": "書類を準備しておく。", "en": "Prepare documents in advance."}, {"jp": "予約しておいた。", "en": "I made a reservation in advance."}], "notes": "Expresses doing something in advance."},
    {"title": "～てある", "meaning": "has been done, is done (state)", "level": "N3", "isImportant": False, "expressions": ["～てある", "～である"], "patterns": ["Verb + てある", "Verb + である"], "examples": [{"jp": "予約してある。", "en": "It has been reserved."}, {"jp": "準備してある。", "en": "It has been prepared."}], "notes": "Expresses a state resulting from a previous action."},
    {"title": "～てしまう", "meaning": "to finish doing, to do completely, to do by mistake", "level": "N3", "isImportant": False, "expressions": ["～てしまう", "～てしまった"], "patterns": ["Verb + てしまう", "Verb + てしまった"], "examples": [{"jp": "書類を忘れてしまった。", "en": "I forgot the documents."}, {"jp": "鍵をなくしてしまった。", "en": "I lost the key."}], "notes": "Expresses completion or regret."},
    {"title": "～ておけば", "meaning": "if I had done~, if I do~ (in advance)", "level": "N2", "isImportant": False, "expressions": ["～ておけば", "～ておけばよかった"], "patterns": ["Verb + ておけば", "Verb + ておけばよかった"], "examples": [{"jp": "前もって申請しておけばよかった。", "en": "I wish I had applied in advance."}, {"jp": "保険に入っておけば安心だ。", "en": "I'd feel better if I had insurance."}], "notes": "Expresses conditional with preparation."},
    {"title": "～とく", "meaning": "to do in advance (casual)", "level": "N2", "isImportant": False, "expressions": ["～とく", "～といた"], "patterns": ["Verb + とく", "Verb + といた"], "examples": [{"jp": "予約しとく。", "en": "I'll reserve it (in advance)."}, {"jp": "準備しといた。", "en": "I prepared it (in advance)."}], "notes": "Casual contraction of ておく."},
    {"title": "～ちゃう", "meaning": "to do completely, to do by mistake (casual)", "level": "N2", "isImportant": False, "expressions": ["～ちゃう", "～ちゃった"], "patterns": ["Verb + ちゃう", "Verb + ちゃった"], "examples": [{"jp": "書類を忘れちゃった。", "en": "I forgot the documents."}, {"jp": "鍵をなくしちゃった。", "en": "I lost the key."}], "notes": "Casual contraction of てしまう."},
    {"title": "～ちまう", "meaning": "to do completely, to do by mistake (casual, masculine)", "level": "N2", "isImportant": False, "expressions": ["～ちまう", "～ちまった"], "patterns": ["Verb + ちまう", "Verb + ちまった"], "examples": [{"jp": "書類を忘れちまった。", "en": "I forgot the documents."}, {"jp": "鍵をなくしちまった。", "en": "I lost the key."}], "notes": "Casual contraction of てしまう, more masculine."},
    {"title": "～てたまらない", "meaning": "can't help but~, extremely~, unbearably~", "level": "N2", "isImportant": False, "expressions": ["～てたまらない", "～てたまらないほど"], "patterns": ["Verb/Adj + てたまらない"], "examples": [{"jp": "不安でたまらない。", "en": "I can't help but feel anxious."}, {"jp": "心配でたまらない。", "en": "I'm unbearably worried."}], "notes": "Expresses strong feeling."},
    {"title": "～てならない", "meaning": "can't help but~, extremely~", "level": "N2", "isImportant": False, "expressions": ["～てならない", "～てならないほど"], "patterns": ["Verb/Adj + てならない"], "examples": [{"jp": "不安でならない。", "en": "I can't help but feel anxious."}, {"jp": "心配でならない。", "en": "I'm extremely worried."}], "notes": "Expresses strong feeling, more formal than たまらない."},
    {"title": "～ざるを得ない", "meaning": "cannot help but~, have no choice but to~", "level": "N1", "isImportant": False, "expressions": ["～ざるを得ない", "～ざるをえない"], "patterns": ["Verb + ざるを得ない"], "examples": [{"jp": "留学を諦めざるを得ない。", "en": "I have no choice but to give up studying abroad."}, {"jp": "変更せざるを得ない。", "en": "I have no choice but to change it."}], "notes": "Formal expression of having no choice."},
    {"title": "～ないわけにはいかない", "meaning": "cannot not~, must~", "level": "N2", "isImportant": False, "expressions": ["～ないわけにはいかない", "～ないわけにはいかない"], "patterns": ["Verb + ないわけにはいかない"], "examples": [{"jp": "申請しないわけにはいかない。", "en": "I must apply."}, {"jp": "勉強しないわけにはいかない。", "en": "I must study."}], "Notes": "Expresses obligation or necessity."},
    {"title": "～ないものか", "meaning": "isn't there a way to~, can't I~", "level": "N2", "isImportant": False, "expressions": ["～ないものか", "～ないものだろうか"], "patterns": ["Verb + ないものか", "Verb + ないものだろうか"], "examples": [{"jp": "もっと安く留学できないものか。", "en": "Isn't there a way to study abroad more cheaply?"}, {"jp": "早く終わらないものか。", "en": "Can't it finish sooner?"}], "notes": "Expresses hope or wish."},
    {"title": "～ないとも限らない", "meaning": "not necessarily~, might~", "level": "N2", "isImportant": False, "expressions": ["～ないとも限らない", "～ないとも限らない"], "patterns": ["Verb + ないとも限らない", "Adj + ないとも限らない"], "examples": [{"jp": "遅れないとも限らない。", "en": "It's not certain that I won't be late."}, {"jp": "安くないとも限らない。", "en": "It's not certain that it won't be cheap."}], "notes": "Expresses possibility or uncertainty."},
]

# ========== SCENES (10) ==========
scenes = [
    {"title": "空港での入国審査", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "審査官", "jp": "目的は何ですか？", "en": "What is the purpose of your visit?"}, {"speaker": "学生", "jp": "留学です。", "en": "I'm here to study abroad."}, {"speaker": "審査官", "jp": "期間はどのくらいですか？", "en": "How long is your stay?"}, {"speaker": "学生", "jp": "二年間です。", "en": "For two years."}, {"speaker": "審査官", "jp": "住宿先は？", "en": "Where will you stay?"}, {"speaker": "学生", "jp": "学生寮です。", "en": "In a student dormitory."}, {"speaker": "審査官", "jp": "はい、どうぞ。", "en": "Alright, go ahead."}]},
    {"title": "留学相談", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "留学したいんですが、どこがいいですか？", "en": "I want to study abroad, where is good?"}, {"speaker": "カウンセラー", "jp": "どの国に行きたいですか？", "en": "Which country do you want to go to?"}, {"speaker": "学生", "jp": "アメリカかカナダで迷ってます。", "en": "I'm torn between America and Canada."}, {"speaker": "カウンセラー", "jp": "アメリカは選択肢が多いですが、費用が高いです。", "en": "America has many options, but it's expensive."}, {"speaker": "学生", "jp": "奨学金はありますか？", "en": "Are there scholarships?"}, {"speaker": "カウンセラー", "jp": "いくつかありますので、ご案内します。", "en": "There are several, so I'll show you."}]},
    {"title": "アパートを借りる", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "アパートを探しているんですが。", "en": "I'm looking for an apartment."}, {"speaker": "不動産屋", "jp": "予算はどのくらいですか？", "en": "What's your budget?"}, {"speaker": "学生", "jp": "5万円以下で、駅から近いところがいいです。", "en": "Under 50,000 yen, close to the station."}, {"speaker": "不動産屋", "jp": "このアパートはどうですか？駅から徒歩5分です。", "en": "How about this apartment? It's 5 minutes walk from the station."}, {"speaker": "学生", "jp": "家賃はいくらですか？", "en": "How much is the rent?"}, {"speaker": "不動産屋", "jp": "4万8千円です。", "en": "It's 48,000 yen."}, {"speaker": "学生", "jp": "契約したいです。", "en": "I'd like to sign a contract."}]},
    {"title": "寮の入寮手続き", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "入寮の手続きをしたいんですが。", "en": "I want to complete the check-in procedure."}, {"speaker": "管理人", "jp": "名前と学籍番号をお願いします。", "en": "Please give me your name and student ID."}, {"speaker": "学生", "jp": "山田太郎、学籍番号は123456です。", "en": "Taro Yamada, student ID is 123456."}, {"speaker": "管理人", "jp": "これは寮の規則です。", "en": "These are the dormitory rules."}, {"speaker": "学生", "jp": "門限は何時ですか？", "en": "What time is curfew?"}, {"speaker": "管理人", "jp": "11時です。遅れる場合は連絡してください。", "en": "It's 11 PM. Please contact us if you'll be late."}]},
    {"title": "病院での診察", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "お腹が痛いんです。", "en": "My stomach hurts."}, {"speaker": "医者", "jp": "いつからですか？", "en": "Since when?"}, {"speaker": "学生", "jp": "昨日からです。", "en": "Since yesterday."}, {"speaker": "医者", "jp": "熱はありますか？", "en": "Do you have a fever?"}, {"speaker": "学生", "jp": "少しあります。", "en": "A little."}, {"speaker": "医者", "jp": "薬を出しますので、ゆっくり休んでください。", "en": "I'll give you medicine, so rest well."}, {"speaker": "学生", "jp": "保険は使えますか？", "en": "Can I use insurance?"}, {"speaker": "医者", "jp": "はい、使えます。", "en": "Yes, you can."}]},
    {"title": "銀行で口座を開く", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "銀行口座を開きたいんですが。", "en": "I want to open a bank account."}, {"speaker": "銀行員", "jp": "パスポートと在留カードをお願いします。", "en": "Please give me your passport and residence card."}, {"speaker": "学生", "jp": "はい、どうぞ。", "en": "Here you go."}, {"speaker": "銀行員", "jp": "こちらにサインをお願いします。", "en": "Please sign here."}, {"speaker": "学生", "jp": "キャッシュカードはいつもらえますか？", "en": "When can I get the cash card?"}, {"speaker": "銀行員", "jp": "一週間後に届きます。", "en": "It will arrive in a week."}]},
    {"title": "携帯電話を契約する", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "携帯電話を契約したいんですが。", "en": "I want to sign up for a mobile phone."}, {"speaker": "店員", "jp": "どのプランがいいですか？", "en": "Which plan would you like?"}, {"speaker": "学生", "jp": "安いプランはありますか？", "en": "Is there a cheap plan?"}, {"speaker": "店員", "jp": "このプランは月額2000円です。", "en": "This plan is 2000 yen per month."}, {"speaker": "学生", "jp": "契約期間は？", "en": "What's the contract period?"}, {"speaker": "店員", "jp": "一年間です。", "en": "It's one year."}, {"speaker": "学生", "jp": "契約します。", "en": "I'll sign up."}]},
    {"title": "学校のオリエンテーション", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "先生", "jp": "ようこそ。今日は学校の案内をします。", "en": "Welcome. Today I'll show you around the school."}, {"speaker": "学生", "jp": "よろしくお願いします。", "en": "Nice to meet you."}, {"speaker": "先生", "jp": "これは学校の地図です。", "en": "This is a map of the school."}, {"speaker": "学生", "jp": "図書館はどこですか？", "en": "Where is the library?"}, {"speaker": "先生", "jp": "あの建物の2階です。", "en": "On the second floor of that building."}, {"speaker": "学生", "jp": "ありがとうございます。", "en": "Thank you."}]},
    {"title": "郵便局で手紙を送る", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "この手紙を送りたいんですが。", "en": "I want to send this letter."}, {"speaker": "局員", "jp": "航空便ですか、船便ですか？", "en": "Air mail or sea mail?"}, {"speaker": "学生", "jp": "航空便でお願いします。", "en": "Air mail please."}, {"speaker": "局員", "jp": "アメリカまでですか？", "en": "To America?"}, {"speaker": "学生", "jp": "はい。", "en": "Yes."}, {"speaker": "局員", "jp": "200円です。", "en": "It's 200 yen."}, {"speaker": "学生", "jp": "いくらですか？", "en": "How much is it?"}]},
    {"title": "警察署に届け出る", "level": "N3", "isImportant": False, "dialogues": [{"speaker": "学生", "jp": "財布を盗まれたんですが。", "en": "My wallet was stolen."}, {"speaker": "警察", "jp": "いつ、どこでですか？", "en": "When and where?"}, {"speaker": "学生", "jp": "昨日、駅でです。", "en": "Yesterday, at the station."}, {"speaker": "警察", "jp": "中身は何が入っていましたか？", "en": "What was inside?"}, {"speaker": "学生", "jp": "現金とクレジットカードです。", "en": "Cash and a credit card."}, {"speaker": "警察", "jp": "盗難届を出します。", "en": "I'll file a theft report."}, {"speaker": "学生", "jp": "カードを止めたいんですが。", "en": "I want to cancel the card."}, {"speaker": "警察", "jp": "カード会社にも連絡してください。", "en": "Please contact the card company too."}]},
]

# ========== TOPICS (6) ==========
topics = [
    {"title": "留学の準備と手続き", "level": "N3", "body": "留学を決めたら、まずビザの申請が必要です。ビザには種類があり、留学ビザは「留学」または「就学」ビザと呼ばれます。\n\n必要な書類は以下の通りです：パスポート、入学許可書、資金証明書、履歴書、写真など。申請には数週間かかるため、早めに準備しましょう。\n\nまた、滞在先も重要です。学生寮、下宿、アパートなどがあります。学生寮は安いですが、規則が厳しいです。アパートは自由ですが、家賃が高いです。\n\n留学前に、保険にも加入しておきましょう。病気や怪我の時に安心です。", "questions": [{"question": "留学に必要な書類でないものは？", "options": ["A. パスポート", "B. 入学許可書", "C. 運転免許証", "D. 写真"], "answer": "C"}, {"question": "学生寮の特徴は？", "options": ["A. 家賃が高い", "B. 規則が厳しい", "C. 自由だ", "D. 手続きが不要"], "answer": "B"}]},
    {"title": "留学先での生活", "level": "N3", "body": "留学先での生活は、最初は大変です。言葉の壁、文化の違い、食事の違いなど、さまざまな困難があります。\n\nまず、生活費を管理しましょう。家賃、食費、光熱費、交通費などを把握し、予算を立てます。奨学金がある場合は、申請を忘れずに。\n\nまた、病気や怪我の時は、病院に行きましょう。保険があると、費用を抑えられます。緊急時は警察に連絡します。\n\n友達を作ることも大切です。学校の友達、ルームメイト、近所の人など、さまざまな人と交流しましょう。言葉の上達にも役立ちます。", "questions": [{"question": "留学先で大切なことは？", "options": ["A. 生活費を管理する", "B. 予算を立てない", "C. 病院に行かない", "D. 友達を作らない"], "answer": "A"}, {"question": "保険の役割は？", "options": ["A. 費用を増やす", "B. 費用を抑える", "C. 病気を防ぐ", "D. 友達を作る"], "answer": "B"}]},
    {"title": "留学のビザ申請", "level": "N2", "body": "留学ビザを申請するには、まず入学許可書が必要です。学校に合格されたら、入学許可書が送られてきます。\n\n次に、資金証明書を準備します。留学中の生活費と学費を支払えることを証明する必要があります。銀行の残高証明や、奨学金の証明書などが必要です。\n\n申請は日本大使館または領事館で行います。必要な書類をすべて提出し、審査を受けます。審査には数週間かかることがあります。\n\nビザが承認されたら、パスポートにビザが貼られます。その後、日本に入国できます。入国時に、入国審査でビザとパスポートを提示します。", "questions": [{"question": "ビザ申請に必要なものは？", "options": ["A. 入学許可書", "B. 運転免許証", "C. 健康診断書", "D. 推薦状"], "answer": "A"}, {"question": "資金証明書の目的は？", "options": ["A. 学力を証明する", "B. 支払い能力を証明する", "C. 健康を証明する", "D. 身分を証明する"], "answer": "B"}]},
    {"title": "留学先の住居選び", "level": "N2", "body": "留学先の住居には、いくつか選択肢があります。それぞれ特徴が異なります。\n\n学生寮は、学校に近く、家賃が安いです。しかし、規則が厳しく、プライバシーが少ないです。門限やルールを守る必要があります。\n\n下宿は、日本人の家に住み込む形態です。食事が出ることもありますが、規則が多いです。\n\nアパートは、自由度が高いです。しかし、家賃が高く、契約の手続きも面倒です。保証人や初期費用が必要です。\n\n自分のライフスタイルに合った住居を選びましょう。", "questions": [{"question": "学生寮の特徴は？", "options": ["A. 自由度が高い", "B. 家賃が安い", "C. 規則がない", "D. プライバシーが多い"], "answer": "B"}, {"question": "アパートの特徴は？", "options": ["A. 家賃が安い", "B. 自由度が高い", "C. 規則が厳しい", "D. 食事が出る"], "answer": "B"}]},
    {"title": "留学中の健康管理", "level": "N2", "body": "留学中は、健康管理が大切です。新しい環境では、体調を崩しやすくなります。\n\nまず、食事に気をつけましょう。日本は食事が違います。栄養のバランスを考えて食事をしましょう。\n\nまた、運動も大切です。適度な運動をして、体力を保ちましょう。\n\n病気や怪我の時は、病院に行きましょう。保険に加入しておくと、費用を抑えられます。緊急時は、警察や救急車に連絡します。\n\n日本では、健康保険に加入する必要があります。保険料を払えば、医療費の30%で済みます。", "questions": [{"question": "留学中に大切なことは？", "options": ["A. 健康管理", "B. 食事を気にしない", "C. 運動しない", "D. 病院に行かない"], "answer": "A"}, {"question": "健康保険の役割は？", "options": ["A. 医療費を増やす", "B. 医療費を抑える", "C. 病気を防ぐ", "D. 怪我を防ぐ"], "answer": "B"}]},
    {"title": "留学の奨学金制度", "level": "N2", "body": "留学する場合、費用がかかります。学費、生活費、渡航費など、多くの費用が必要です。\n\n奨学金制度を利用すれば、費用を抑えられます。奨学金には、給付型と貸与型があります。給付型は返済不要ですが、競争率が高いです。\n\n奨学金を申請するには、成績や経済状況などの条件があります。早めに情報を集め、準備しましょう。\n\nまた、アルバイトをして稼こともできます。しかし、ビザの制限があるため、週28時間以内です。学業に支障が出ないようにしましょう。", "questions": [{"question": "奨学金の給付型の特徴は？", "options": ["A. 返済が必要", "B. 返済不要", "C. 競争率が低い", "D. 条件がない"], "answer": "B"}, {"question": "アルバイトの制限は？", "options": ["A. 週14時間以内", "B. 週28時間以内", "C. 週40時間以内", "D. 制限なし"], "answer": "B"}]},
]

# ========== Write files ==========
def write_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

write_json(DATA_DIR / "new_words.json", words)
write_json(DATA_DIR / "new_grammar.json", grammar)
write_json(DATA_DIR / "new_scenes.json", scenes)
write_json(DATA_DIR / "new_topics.json", topics)

print(f"Generated: {len(words)} words, {len(grammar)} grammar, {len(scenes)} scenes, {len(topics)} topics")
